database_path = "./database.db"
# The command will be run with CWD set to exploits_path
flagger_command = "python3 flagger.py"
exploits_path = "./exploits"
tick_time = 10000 # in ms
flag_regex = "FLAG{.*}"
timezone = "Europe/Bucharest"
time_format = "2006-01-02 15:04:05"
listening_addr = "127.0.0.1:8080"